version: '3'

services:
    ht-database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
            ENVIRONMENT: "${ENVIRONMENT}"
        volumes:
            - ./database/:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
        ports:
            - "${HOST_ADDR}:5432:5432"
             
volumes:
    db-data: